const DocumentRequest = require("../models/DocumentRequest");
const Employee = require("../models/Employees");
const Settings = require("../models/Settings");
const { generateSalaryCertificateForEmployee } = require("../routes/docs");
const { approvedFields } = require("../utils/requestAutoApproval");

const getUserId = (req) => req.user?._id || req.employee?._id;
const getOwnerId = (req) => req.user?.owner || req.employee?.owner;

exports.applyDocumentRequest = async (req, res) => {
  try {
    const { documentType, month, purpose, copyType, reason } = req.body;
    const employeeId = req.employee?._id;
    const ownerId = getOwnerId(req);

    if (!documentType) return res.status(400).json({ message: "Document type is required" });
    if (!["salary-slip", "salary-certificate"].includes(documentType)) {
      return res.status(400).json({ message: "Invalid document type" });
    }

    // Salary certificate requires a copy type
    if (documentType === "salary-certificate" && !["soft-copy", "hard-copy", "attested"].includes(copyType)) {
      return res.status(400).json({ message: "Please specify how you'd like to receive the certificate (soft-copy, hard-copy, or attested)" });
    }

    // Check if soft-copy auto-generation is enabled for this owner
    const isSoftCopy = documentType === "salary-certificate" && copyType === "soft-copy";
    let autoGenerate = false;
    if (isSoftCopy) {
      const ownerSettings = await Settings.findOne({ owner: ownerId }).lean();
      autoGenerate = ownerSettings?.autoGenerateSalaryCertificate === true;
    }

    const newRequest = new DocumentRequest({
      employee: employeeId,
      owner: ownerId,
      documentType,
      month: documentType === "salary-slip" ? (month || undefined) : undefined,
      purpose: purpose || undefined,
      copyType: documentType === "salary-certificate" ? copyType : undefined,
      reason: reason || undefined,
      ...approvedFields(req),
    });

    await newRequest.save();

    // Auto-generate the certificate PDF for approved soft-copy requests if setting is enabled
    if (autoGenerate && newRequest.status === "approved") {
      try {
        const { saveResult, referenceNumber } = await generateSalaryCertificateForEmployee(
          String(employeeId),
          String(ownerId)
        );
        if (saveResult.success) {
          newRequest.generatedDocUrl = saveResult.url;
          newRequest.referenceNumber = referenceNumber;
          await newRequest.save();
        }
      } catch (genErr) {
        console.error("Auto-generation of salary certificate failed:", genErr.message);
      }
    }

    res.status(201).json({
      message: autoGenerate && newRequest.status === "approved"
        ? "Salary certificate generated automatically. You can download it now."
        : newRequest.status === "approved" ? "Document request approved successfully" : "Document request submitted successfully",
      data: newRequest,
      autoGenerated: autoGenerate,
    });
  } catch (error) {
    console.error("DocumentRequest Apply Error:", error);
    res.status(500).json({ message: error.message });
  }
};

exports.getMyRequests = async (req, res) => {
  try {
    const employeeId = req.employee?._id;
    const filter = { employee: employeeId };
    if (req.query.documentType) filter.documentType = req.query.documentType;
    const requests = await DocumentRequest.find(filter)
      .populate("employee", "name designation department photographUrl")
      .sort({ createdAt: -1 });
    res.status(200).json({ data: requests });
  } catch (error) {
    console.error("DocumentRequest GetMy Error:", error);
    res.status(500).json({ message: error.message });
  }
};

exports.getAllRequests = async (req, res) => {
  try {
    const ownerId = getOwnerId(req);
    const { status, documentType, month } = req.query;
    const filter = { owner: ownerId };
    if (status) filter.status = status;
    if (documentType) filter.documentType = documentType;
    if (month) filter.month = month;

    const requests = await DocumentRequest.find(filter)
      .populate("employee", "name designation department photographUrl")
      .sort({ createdAt: -1 });
    res.status(200).json({ data: requests });
  } catch (error) {
    console.error("DocumentRequest GetAll Error:", error);
    res.status(500).json({ message: error.message });
  }
};

exports.updateStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status, adminReason } = req.body;

    if (!["approved", "rejected"].includes(status)) {
      return res.status(400).json({ message: "Invalid status" });
    }

    const reviewerId = req.employee?._id || req.user?.employeeId || req.user?.employeeInfo?.employeeId || getUserId(req);
    const updateData = { status, adminReason, reviewedBy: reviewerId };
    if (status === "approved") {
      updateData.approvedBy = getUserId(req);
      updateData.approvedAt = new Date();
    }

    const request = await DocumentRequest.findByIdAndUpdate(id, updateData, { new: true })
      .populate("employee", "name designation department companyEmail");
    if (!request) return res.status(404).json({ message: "Request not found" });

    // Auto-generate salary certificate PDF on approval
    if (status === "approved" && request.documentType === "salary-certificate") {
      try {
        const { saveResult, referenceNumber } = await generateSalaryCertificateForEmployee(
          String(request.employee._id || request.employee),
          String(request.owner)
        );

        if (saveResult.success) {
          request.generatedDocUrl = saveResult.url;
          request.referenceNumber = referenceNumber;
          await DocumentRequest.findByIdAndUpdate(id, {
            generatedDocUrl: saveResult.url,
            referenceNumber,
          });
        }
      } catch (genErr) {
        console.error("Salary certificate generation failed:", genErr.message);
        // Don't fail the approval — just log and continue without a URL
      }
    }

    // Notify employee via socket
    const io = req.app.get("io");
    if (io) {
      const empId = String(request.employee._id || request.employee);
      io.to(`employee_${empId}`).emit("document_request_updated", {
        requestId: String(request._id),
        documentType: request.documentType,
        copyType: request.copyType || null,
        status,
        referenceNumber: request.referenceNumber || null,
        generatedDocUrl: request.generatedDocUrl || null,
        message: status === "approved"
          ? `Your salary certificate request has been approved.${request.generatedDocUrl ? " Your certificate is ready to download." : ""}`
          : `Your salary certificate request was rejected. ${adminReason || ""}`.trim(),
      });
    }

    res.status(200).json({ message: `Document request ${status}`, data: request });
  } catch (error) {
    console.error("DocumentRequest UpdateStatus Error:", error);
    res.status(500).json({ message: error.message });
  }
};

exports.deleteRequest = async (req, res) => {
  try {
    const { id } = req.params;
    const ownerId = getOwnerId(req);
    const deleted = await DocumentRequest.findOneAndDelete({ _id: id, owner: ownerId });
    if (!deleted) return res.status(404).json({ message: "Request not found" });
    res.status(200).json({ message: "Document request deleted" });
  } catch (error) {
    console.error("DocumentRequest Delete Error:", error);
    res.status(500).json({ message: error.message });
  }
};
